# Generated by Django 6.0.1 on 2026-02-06 17:54

import photos.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_alter_photo_tagged_pets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(max_length=1000, upload_to='', validators=[photos.validators.FileSizeValidator(5)]),
        ),
    ]
