# Generated by Django 6.0.1 on 2026-02-06 20:21

import photos.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_alter_photo_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(max_length=1000, upload_to='media', validators=[photos.validators.FileSizeValidator(5)]),
        ),
    ]
