# Generated by Django 6.0.1 on 2026-01-27 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('rating', models.DecimalField(decimal_places=2, max_digits=4)),
                ('is_verified', models.BooleanField(default=False)),
                ('review_type', models.CharField(choices=[('Text', 'Text'), ('Video', 'Video'), ('Audio', 'Audio')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book')),
            ],
        ),
    ]
