# Generated by Django 6.0.1 on 2026-01-08 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_note_priority_note_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='note',
            name='priority',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
