# Generated by Django 6.0.1 on 2026-01-20 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='date_and_tine_of_pulication',
            new_name='date_and_tine_of_publication',
        ),
    ]
