# Generated by Django 6.0.1 on 2026-02-06 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_rename_date_and_tine_of_pulication_comment_date_and_tine_of_publication'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-date_and_time_of_publication',)},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='date_and_tine_of_publication',
            new_name='date_and_time_of_publication',
        ),
    ]
