# Generated by Django 6.0.1 on 2026-01-27 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('isbn', models.CharField(max_length=13, unique=True)),
                ('genre', models.CharField(choices=[('Fiction', 'Fiction'), ('Non-Fiction', 'Non-Fiction'), ('Fantasy', 'Fantasy'), ('Science', 'Science')])),
                ('language', models.CharField(choices=[('Bulgarian', 'Bulgarian'), ('English', 'English'), ('French', 'French'), ('German', 'German'), ('Other', 'Other')])),
                ('pages', models.PositiveIntegerField()),
                ('is_available', models.BooleanField(default=True)),
                ('publishing_date', models.DateField()),
                ('description', models.TextField()),
                ('image_url', models.URLField()),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
